# Generated by Django 2.1.1 on 2018-11-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('image', models.URLField(max_length=120)),
                ('description', models.TextField()),
                ('brand_name', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='account.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customarName', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_numbe', models.CharField(blank=True, max_length=15, null=True)),
                ('due', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentType', to='account.Payment')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_products', to='account.Product')),
            ],
        ),
    ]
