# Generated by Django 2.1.1 on 2018-11-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_in', models.IntegerField(default=0)),
                ('stock_out', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('deu_amount', models.IntegerField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('wholesale', models.IntegerField()),
                ('barcode', models.CharField(max_length=60)),
                ('invoice', models.IntegerField(unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='agents.Vendors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categorys', to='account.Category')),
                ('pay_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to='account.Payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockin_product', to='account.Product')),
            ],
        ),
    ]
