# Generated by Django 2.1.1 on 2018-11-14 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=14)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=70)),
                ('nid_card', models.IntegerField(unique=True)),
                ('profile_pic', models.URLField(max_length=70)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('agent_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_names', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
